"""Add washability and yield models

Revision ID: 0128b9f78ffc
Revises: 5212f3c4bf17
Create Date: 2026-01-05 14:54:11.372775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0128b9f78ffc'
down_revision = '5212f3c4bf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('washability_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_number', sa.String(length=50), nullable=True),
    sa.Column('sample_name', sa.String(length=100), nullable=True),
    sa.Column('sample_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('consignor', sa.String(length=100), nullable=True),
    sa.Column('initial_mass_kg', sa.Float(), nullable=True),
    sa.Column('raw_tm', sa.Float(), nullable=True),
    sa.Column('raw_im', sa.Float(), nullable=True),
    sa.Column('raw_ash', sa.Float(), nullable=True),
    sa.Column('raw_vol', sa.Float(), nullable=True),
    sa.Column('raw_sulphur', sa.Float(), nullable=True),
    sa.Column('raw_csn', sa.Float(), nullable=True),
    sa.Column('raw_gi', sa.Float(), nullable=True),
    sa.Column('raw_trd', sa.Float(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('excel_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('washability_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_washability_test_lab_number'), ['lab_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_sample_date'), ['sample_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_sample_name'), ['sample_name'], unique=False)

    op.create_table('plant_yield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('coal_source', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('feed_tonnes', sa.Float(), nullable=True),
    sa.Column('product_tonnes', sa.Float(), nullable=True),
    sa.Column('actual_yield', sa.Float(), nullable=True),
    sa.Column('feed_ash', sa.Float(), nullable=True),
    sa.Column('product_ash', sa.Float(), nullable=True),
    sa.Column('washability_test_id', sa.Integer(), nullable=True),
    sa.Column('theoretical_yield', sa.Float(), nullable=True),
    sa.Column('recovery_efficiency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['washability_test_id'], ['washability_test.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_yield', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_yield_production_date'), ['production_date'], unique=False)

    op.create_table('theoretical_yield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('target_ash', sa.Float(), nullable=False),
    sa.Column('size_fraction', sa.String(length=20), nullable=True),
    sa.Column('theoretical_yield', sa.Float(), nullable=True),
    sa.Column('actual_yield', sa.Float(), nullable=True),
    sa.Column('recovery_efficiency', sa.Float(), nullable=True),
    sa.Column('ngm_plus_01', sa.Float(), nullable=True),
    sa.Column('ngm_plus_02', sa.Float(), nullable=True),
    sa.Column('separation_density', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['washability_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theoretical_yield', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theoretical_yield_test_id'), ['test_id'], unique=False)

    op.create_table('washability_fraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('size_fraction', sa.String(length=20), nullable=True),
    sa.Column('size_upper', sa.Float(), nullable=True),
    sa.Column('size_lower', sa.Float(), nullable=True),
    sa.Column('size_mass_kg', sa.Float(), nullable=True),
    sa.Column('density_sink', sa.Float(), nullable=True),
    sa.Column('density_float', sa.Float(), nullable=True),
    sa.Column('mass_gram', sa.Float(), nullable=True),
    sa.Column('mass_percent', sa.Float(), nullable=True),
    sa.Column('im_percent', sa.Float(), nullable=True),
    sa.Column('ash_ad', sa.Float(), nullable=True),
    sa.Column('vol_ad', sa.Float(), nullable=True),
    sa.Column('sulphur_ad', sa.Float(), nullable=True),
    sa.Column('csn', sa.Float(), nullable=True),
    sa.Column('cumulative_yield', sa.Float(), nullable=True),
    sa.Column('cumulative_ash', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['washability_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('washability_fraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_washability_fraction_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('system_license', schema=None) as batch_op:
        batch_op.alter_column('license_key',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_license', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('license_key',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('washability_fraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_washability_fraction_test_id'))

    op.drop_table('washability_fraction')
    with op.batch_alter_table('theoretical_yield', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theoretical_yield_test_id'))

    op.drop_table('theoretical_yield')
    with op.batch_alter_table('plant_yield', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_yield_production_date'))

    op.drop_table('plant_yield')
    with op.batch_alter_table('washability_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_washability_test_sample_name'))
        batch_op.drop_index(batch_op.f('ix_washability_test_sample_date'))
        batch_op.drop_index(batch_op.f('ix_washability_test_lab_number'))

    op.drop_table('washability_test')
    # ### end Alembic commands ###
