"""Add SparePart SparePartUsage SparePartLog models

Revision ID: 0d249829b308
Revises: 78182c9ac185
Create Date: 2026-02-04 02:56:20.029114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d249829b308'
down_revision = '78182c9ac185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('storage_location', sa.String(length=150), nullable=True),
    sa.Column('compatible_equipment', sa.Text(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('usage_life_months', sa.Integer(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_status'), ['status'], unique=False)

    op.create_table('spare_part_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('quantity_change', sa.Float(), nullable=True),
    sa.Column('quantity_before', sa.Float(), nullable=True),
    sa.Column('quantity_after', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_log_spare_part_id'), ['spare_part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_log_user_id'), ['user_id'], unique=False)

    op.create_table('spare_part_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_log_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('quantity_before', sa.Float(), nullable=True),
    sa.Column('quantity_after', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_log_id'], ['maintenance_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_part.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_usage_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_usage_spare_part_id'), ['spare_part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_part_usage_used_by_id'), ['used_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_usage_used_by_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_usage_spare_part_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_usage_equipment_id'))

    op.drop_table('spare_part_usage')
    with op.batch_alter_table('spare_part_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_spare_part_log_spare_part_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_log_action'))

    op.drop_table('spare_part_log')
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_status'))
        batch_op.drop_index(batch_op.f('ix_spare_part_part_number'))
        batch_op.drop_index(batch_op.f('ix_spare_part_name'))
        batch_op.drop_index(batch_op.f('ix_spare_part_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_spare_part_category'))

    op.drop_table('spare_part')
    # ### end Alembic commands ###
