"""Add equipment tables

Revision ID: 14795e47a81c
Revises: acda052ec4a8
Create Date: 2025-11-20 12:45:15.790769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14795e47a81c'
down_revision = 'acda052ec4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('related_analysis', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('related_analysis')
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###
