"""Add Chemical, ChemicalUsage, ChemicalLog models

Revision ID: 19f4cf7409b2
Revises: 202602030002
Create Date: 2026-02-04 01:21:55.529039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f4cf7409b2'
down_revision = '202602030002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cas_number', sa.String(length=50), nullable=True),
    sa.Column('formula', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('catalog_number', sa.String(length=100), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('storage_conditions', sa.String(length=200), nullable=True),
    sa.Column('hazard_class', sa.String(length=100), nullable=True),
    sa.Column('sds_file_path', sa.String(length=255), nullable=True),
    sa.Column('lab_type', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_lab_type'), ['lab_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_status'), ['status'], unique=False)

    op.create_table('chemical_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('quantity_change', sa.Float(), nullable=True),
    sa.Column('quantity_before', sa.Float(), nullable=True),
    sa.Column('quantity_after', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chemical_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_log_chemical_id'), ['chemical_id'], unique=False)
        batch_op.create_index('ix_chemical_log_chemical_timestamp', ['chemical_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_log_user_id'), ['user_id'], unique=False)

    op.create_table('chemical_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analysis_code', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('quantity_before', sa.Float(), nullable=True),
    sa.Column('quantity_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chemical_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_usage_chemical_id'), ['chemical_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_usage_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_usage_used_by_id'), ['used_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_usage_used_by_id'))
        batch_op.drop_index(batch_op.f('ix_chemical_usage_used_at'))
        batch_op.drop_index(batch_op.f('ix_chemical_usage_chemical_id'))

    op.drop_table('chemical_usage')
    with op.batch_alter_table('chemical_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_chemical_log_timestamp'))
        batch_op.drop_index('ix_chemical_log_chemical_timestamp')
        batch_op.drop_index(batch_op.f('ix_chemical_log_chemical_id'))
        batch_op.drop_index(batch_op.f('ix_chemical_log_action'))

    op.drop_table('chemical_log')
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_status'))
        batch_op.drop_index(batch_op.f('ix_chemical_name'))
        batch_op.drop_index(batch_op.f('ix_chemical_lab_type'))
        batch_op.drop_index(batch_op.f('ix_chemical_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_chemical_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_chemical_category'))

    op.drop_table('chemical')
    # ### end Alembic commands ###
