"""feat: Chemical-д expiry alert opened_expiry GHS талбар нэмэх

Revision ID: 23d3a3d7c5a3
Revises: cbf4fe41f6f3
Create Date: 2026-04-05 00:37:56.906157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23d3a3d7c5a3'
down_revision = 'cbf4fe41f6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_worksheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_code', sa.String(length=50), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('primary_reagent_lot_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['primary_reagent_lot_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_worksheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_worksheet_method_code'), ['method_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_worksheet_status'), ['status'], unique=False)
        batch_op.create_index('ix_ws_analyst_date', ['analyst_id', 'analysis_date'], unique=False)
        batch_op.create_index('ix_ws_method_date', ['method_code', 'analysis_date'], unique=False)

    op.create_table('worksheet_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('row_type', sa.String(length=20), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analysis_result_id', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('recovery_pct', sa.Float(), nullable=True),
    sa.Column('rpd_pct', sa.Float(), nullable=True),
    sa.Column('qc_status', sa.String(length=10), nullable=False),
    sa.Column('reagent_lot_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_result.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reagent_lot_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worksheet_id'], ['water_worksheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worksheet_row', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worksheet_row_worksheet_id'), ['worksheet_id'], unique=False)
        batch_op.create_index('ix_wr_sample', ['sample_id'], unique=False)
        batch_op.create_index('ix_wr_worksheet_pos', ['worksheet_id', 'position'], unique=False)

    # Washability tables — зөв дарааллаар drop (FK хамаарлыг харгалзаж)
    op.execute('DROP TABLE IF EXISTS theoretical_yield CASCADE')
    op.execute('DROP TABLE IF EXISTS washability_fraction CASCADE')
    op.execute('DROP TABLE IF EXISTS plant_yield CASCADE')
    op.execute('DROP TABLE IF EXISTS washability_test CASCADE')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_receiver_read', ['receiver_id', 'read_at'], unique=False)
        batch_op.create_index('ix_chat_sender_receiver', ['sender_id', 'receiver_id'], unique=False)

    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_life_after_opening_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opened_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ghs_pictograms', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ghs_signal_word', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sds_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sds_revision_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('days_alert_before_expiry', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prevent_use_if_expired', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_column('prevent_use_if_expired')
        batch_op.drop_column('days_alert_before_expiry')
        batch_op.drop_column('sds_revision_date')
        batch_op.drop_column('sds_version')
        batch_op.drop_column('ghs_signal_word')
        batch_op.drop_column('ghs_pictograms')
        batch_op.drop_column('opened_expiry_date')
        batch_op.drop_column('shelf_life_after_opening_days')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_sender_receiver')
        batch_op.drop_index('ix_chat_receiver_read')

    op.create_table('theoretical_yield',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_ash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('size_fraction', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('theoretical_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recovery_efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ngm_plus_01', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ngm_plus_02', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('separation_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['washability_test.id'], name=op.f('theoretical_yield_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('theoretical_yield_pkey'))
    )
    with op.batch_alter_table('theoretical_yield', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theoretical_yield_test_id'), ['test_id'], unique=False)

    op.create_table('washability_test',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('washability_test_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('lab_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sample_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sample_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('consignor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('initial_mass_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_tm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_im', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_ash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_vol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_sulphur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_csn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_gi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_trd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('excel_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='washability_test_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], name='washability_test_sample_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='washability_test_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('washability_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_washability_test_sample_name'), ['sample_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_sample_date'), ['sample_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_lab_number'), ['lab_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_created_by_id'), ['created_by_id'], unique=False)

    op.create_table('plant_yield',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('production_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('shift', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coal_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('feed_tonnes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('product_tonnes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feed_ash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('product_ash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('washability_test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('theoretical_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recovery_efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['washability_test_id'], ['washability_test.id'], name=op.f('plant_yield_washability_test_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('plant_yield_pkey'))
    )
    with op.batch_alter_table('plant_yield', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_yield_washability_test_id'), ['washability_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plant_yield_production_date'), ['production_date'], unique=False)

    op.create_table('washability_fraction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size_fraction', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('size_upper', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('size_lower', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('size_mass_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('density_sink', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('density_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mass_gram', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mass_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('im_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ash_ad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vol_ad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sulphur_ad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('csn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cumulative_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cumulative_ash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['washability_test.id'], name=op.f('washability_fraction_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('washability_fraction_pkey'))
    )
    with op.batch_alter_table('washability_fraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_washability_fraction_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('worksheet_row', schema=None) as batch_op:
        batch_op.drop_index('ix_wr_worksheet_pos')
        batch_op.drop_index('ix_wr_sample')
        batch_op.drop_index(batch_op.f('ix_worksheet_row_worksheet_id'))

    op.drop_table('worksheet_row')
    with op.batch_alter_table('water_worksheet', schema=None) as batch_op:
        batch_op.drop_index('ix_ws_method_date')
        batch_op.drop_index('ix_ws_analyst_date')
        batch_op.drop_index(batch_op.f('ix_water_worksheet_status'))
        batch_op.drop_index(batch_op.f('ix_water_worksheet_method_code'))

    op.drop_table('water_worksheet')
    # ### end Alembic commands ###
