"""Add error_reason to logs

Revision ID: 24f1b9779172
Revises: a069a860606f
Create Date: 2025-11-18 16:19:38.988021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f1b9779172'
down_revision = 'a069a860606f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.drop_column('error_reason')

    # ### end Alembic commands ###
