"""add version_id and unique constraint to analysis_result

Revision ID: 2e4151c88a54
Revises: 3f8f434aceee
Create Date: 2026-02-27 23:26:29.860006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4151c88a54'
down_revision = '3f8f434aceee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        # server_default='1' → existing rows get version_id=1
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_sample_code'))

    # Давхардсан (sample_id, analysis_code) бүртгэлүүдийг арилгах (хамгийн сүүлийнхийг үлдээнэ)
    op.execute("""
        DELETE FROM analysis_result
        WHERE id NOT IN (
            SELECT MAX(id) FROM analysis_result
            GROUP BY sample_id, analysis_code
        )
    """)

    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sample_analysis_code', ['sample_id', 'analysis_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sample_analysis_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_analysis_result_sample_code'), ['sample_id', 'analysis_code'], unique=False)
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
