"""Add MonthlyPlan model for lab operation planning

Revision ID: 355b372934ee
Revises: 5a12246ee019
Create Date: 2025-12-03 04:20:24.358830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355b372934ee'
down_revision = '5a12246ee019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('sample_type', sa.String(length=100), nullable=False),
    sa.Column('planned_count', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'week', 'client_name', 'sample_type', name='uq_monthly_plan_entry')
    )
    with op.batch_alter_table('monthly_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_plan_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_plan_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_plan_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_plan_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_plan_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_plan_client_name'))

    op.drop_table('monthly_plan')
    # ### end Alembic commands ###
