"""add FK indexes, fix lazy relationships, fix cascade

Revision ID: 3f8f434aceee
Revises: f495c2b86f6d
Create Date: 2026-02-25 19:58:40.157659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8f434aceee'
down_revision = 'f495c2b86f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_result_log_original_user_id'), ['original_user_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_sample_id'), ['sample_id'], unique=False)

    with op.batch_alter_table('chemical_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_usage_sample_id'), ['sample_id'], unique=False)

    with op.batch_alter_table('chemical_waste', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_waste_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('chemical_waste_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_waste_record_recorded_by_id'), ['recorded_by_id'], unique=False)

    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrective_action_responsible_person_id'), ['responsible_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrective_action_technical_manager_id'), ['technical_manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrective_action_verified_by_id'), ['verified_by_id'], unique=False)

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_complaint_capa_id'), ['capa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_complaint_complainant_user_id'), ['complainant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_complaint_investigated_by_id'), ['investigated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_complaint_quality_manager_id'), ['quality_manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_complaint_receiver_user_id'), ['receiver_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_complaint_related_sample_id'), ['related_sample_id'], unique=False)

    with op.batch_alter_table('environmental_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environmental_log_recorded_by_id'), ['recorded_by_id'], unique=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('improvement_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_record_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_record_source_complaint_id'), ['source_complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_record_technical_manager_id'), ['technical_manager_id'], unique=False)

    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_report_analyst_signature_id'), ['analyst_signature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_report_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_report_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_report_manager_signature_id'), ['manager_signature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_report_stamp_id'), ['stamp_id'], unique=False)

    with op.batch_alter_table('license_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_log_license_id'), ['license_id'], unique=False)

    with op.batch_alter_table('monthly_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_plan_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('nonconformity_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonconformity_record_detector_user_id'), ['detector_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nonconformity_record_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nonconformity_record_responsible_user_id'), ['responsible_user_id'], unique=False)

    with op.batch_alter_table('plant_yield', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_yield_washability_test_id'), ['washability_test_id'], unique=False)

    with op.batch_alter_table('proficiency_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proficiency_test_tested_by_id'), ['tested_by_id'], unique=False)

    with op.batch_alter_table('qc_control_chart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_control_chart_operator_id'), ['operator_id'], unique=False)

    with op.batch_alter_table('report_signature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_signature_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_preparation_chemical_id'), ['chemical_id'], unique=False)

    with op.batch_alter_table('solution_recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_recipe_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('solution_recipe_ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_recipe_ingredient_chemical_id'), ['chemical_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_recipe_ingredient_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('spare_part_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_category_equipment_id'), ['equipment_id'], unique=False)

    with op.batch_alter_table('spare_part_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_usage_maintenance_log_id'), ['maintenance_log_id'], unique=False)

    with op.batch_alter_table('washability_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_washability_test_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_washability_test_sample_id'), ['sample_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washability_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_washability_test_sample_id'))
        batch_op.drop_index(batch_op.f('ix_washability_test_created_by_id'))

    with op.batch_alter_table('spare_part_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_usage_maintenance_log_id'))

    with op.batch_alter_table('spare_part_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_category_equipment_id'))

    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_created_by_id'))

    with op.batch_alter_table('solution_recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_recipe_ingredient_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_solution_recipe_ingredient_chemical_id'))

    with op.batch_alter_table('solution_recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_recipe_created_by_id'))

    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_preparation_chemical_id'))

    with op.batch_alter_table('report_signature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_signature_user_id'))

    with op.batch_alter_table('qc_control_chart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_control_chart_operator_id'))

    with op.batch_alter_table('proficiency_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proficiency_test_tested_by_id'))

    with op.batch_alter_table('plant_yield', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_yield_washability_test_id'))

    with op.batch_alter_table('nonconformity_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonconformity_record_responsible_user_id'))
        batch_op.drop_index(batch_op.f('ix_nonconformity_record_manager_id'))
        batch_op.drop_index(batch_op.f('ix_nonconformity_record_detector_user_id'))

    with op.batch_alter_table('monthly_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_plan_created_by_id'))

    with op.batch_alter_table('license_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_log_license_id'))

    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_report_stamp_id'))
        batch_op.drop_index(batch_op.f('ix_lab_report_manager_signature_id'))
        batch_op.drop_index(batch_op.f('ix_lab_report_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_lab_report_approved_by_id'))
        batch_op.drop_index(batch_op.f('ix_lab_report_analyst_signature_id'))

    with op.batch_alter_table('improvement_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_record_technical_manager_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_record_source_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_record_created_by_id'))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_created_by_id'))

    with op.batch_alter_table('environmental_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environmental_log_recorded_by_id'))

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_complaint_related_sample_id'))
        batch_op.drop_index(batch_op.f('ix_customer_complaint_receiver_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_complaint_quality_manager_id'))
        batch_op.drop_index(batch_op.f('ix_customer_complaint_investigated_by_id'))
        batch_op.drop_index(batch_op.f('ix_customer_complaint_complainant_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_complaint_capa_id'))

    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrective_action_verified_by_id'))
        batch_op.drop_index(batch_op.f('ix_corrective_action_technical_manager_id'))
        batch_op.drop_index(batch_op.f('ix_corrective_action_responsible_person_id'))

    with op.batch_alter_table('chemical_waste_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_waste_record_recorded_by_id'))

    with op.batch_alter_table('chemical_waste', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_waste_created_by_id'))

    with op.batch_alter_table('chemical_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_usage_sample_id'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_sample_id'))

    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_original_user_id'))

    # ### end Alembic commands ###
