"""Add file_path to MaintenanceLog

Revision ID: 3fc3552c3075
Revises: 89c8ba0e923e
Create Date: 2025-11-22 14:45:59.795193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc3552c3075'
down_revision = '89c8ba0e923e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
