"""Initial migration from scratch

Revision ID: 4409203ebf97
Revises: 
Create Date: 2025-11-10 01:17:36.766917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4409203ebf97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=200), nullable=True),
    sa.Column('analyses', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_profile_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profile_pattern'), ['pattern'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profile_profile_type'), ['profile_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profile_sample_type'), ['sample_type'], unique=False)

    op.create_table('analysis_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('required_role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('analysis_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_type_required_role'), ['required_role'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_code', sa.String(length=100), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('sample_date', sa.Date(), nullable=True),
    sa.Column('sample_condition', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('analyses_to_perform', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('return_sample', sa.Boolean(), nullable=True),
    sa.Column('delivered_by', sa.String(length=200), nullable=True),
    sa.Column('prepared_by', sa.String(length=200), nullable=True),
    sa.Column('prepared_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('hourly_system', sa.String(length=50), nullable=True),
    sa.Column('shift_time', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_sample_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_received_date'), ['received_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_sample_code'), ['sample_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sample_status'), ['status'], unique=False)

    op.create_table('analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_code', sa.String(length=50), nullable=False),
    sa.Column('final_result', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending_review', nullable=False),
    sa.Column('rejection_category', sa.String(length=100), nullable=True),
    sa.Column('rejection_subcategory', sa.String(length=100), nullable=True),
    sa.Column('rejection_comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_result_analysis_code'), ['analysis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_status'), ['status'], unique=False)

    op.create_table('analysis_result_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('analysis_code', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('raw_data_snapshot', sa.Text(), nullable=True),
    sa.Column('final_result_snapshot', sa.Float(), nullable=True),
    sa.Column('rejection_category', sa.String(length=100), nullable=True),
    sa.Column('rejection_subcategory', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_result.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_result_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_log_analysis_code'), ['analysis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_log_analysis_result_id'), ['analysis_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_log_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_sample_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_analysis_result_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_analysis_code'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_action'))

    op.drop_table('analysis_result_log')
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_result_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_created_at'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_analysis_code'))

    op.drop_table('analysis_result')
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_status'))
        batch_op.drop_index(batch_op.f('ix_sample_sample_code'))
        batch_op.drop_index(batch_op.f('ix_sample_received_date'))

    op.drop_table('sample')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))

    op.drop_table('user')
    with op.batch_alter_table('analysis_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_type_required_role'))

    op.drop_table('analysis_type')
    with op.batch_alter_table('analysis_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_profile_sample_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_profile_profile_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_profile_pattern'))
        batch_op.drop_index(batch_op.f('ix_analysis_profile_client_name'))

    op.drop_table('analysis_profile')
    # ### end Alembic commands ###
