"""Add AuditLog.data_hash

Revision ID: 4d9f2eb4a65c
Revises: e0f07fc98030
Create Date: 2026-02-05 05:50:25.012424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9f2eb4a65c'
down_revision = 'e0f07fc98030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('data_hash')

    # ### end Alembic commands ###
