"""Add composite indexes for Sample and Equipment

Revision ID: 53884d8642d7
Revises: 2e4151c88a54
Create Date: 2026-02-27 23:39:22.598791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53884d8642d7'
down_revision = '2e4151c88a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index('ix_equipment_category_status', ['category', 'status'], unique=False)

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index('ix_sample_client_name_sample_type', ['client_name', 'sample_type'], unique=False)
        batch_op.create_index('ix_sample_lab_type_status', ['lab_type', 'status'], unique=False)
        batch_op.create_index('ix_sample_received_date_lab_type', ['received_date', 'lab_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index('ix_sample_received_date_lab_type')
        batch_op.drop_index('ix_sample_lab_type_status')
        batch_op.drop_index('ix_sample_client_name_sample_type')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index('ix_equipment_category_status')

    # ### end Alembic commands ###
