"""add_iso17025_quality_systems

Revision ID: 5434742346e1
Revises: ee058a56269d
Create Date: 2025-11-30 15:34:55.212498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5434742346e1'
down_revision = 'ee058a56269d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('corrective_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issue_source', sa.String(length=100), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_method', sa.String(length=100), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('responsible_person_id', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('verification_method', sa.Text(), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('effectiveness', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrective_action_ca_number'), ['ca_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_corrective_action_status'), ['status'], unique=False)

    op.create_table('environmental_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('humidity_min', sa.Float(), nullable=True),
    sa.Column('humidity_max', sa.Float(), nullable=True),
    sa.Column('within_limits', sa.Boolean(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environmental_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environmental_log_log_date'), ['log_date'], unique=False)

    op.create_table('proficiency_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_provider', sa.String(length=150), nullable=True),
    sa.Column('pt_program', sa.String(length=100), nullable=True),
    sa.Column('round_number', sa.String(length=50), nullable=True),
    sa.Column('sample_code', sa.String(length=100), nullable=True),
    sa.Column('analysis_code', sa.String(length=50), nullable=True),
    sa.Column('our_result', sa.Float(), nullable=True),
    sa.Column('assigned_value', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('performance', sa.String(length=30), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('certificate_file', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tested_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proficiency_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proficiency_test_analysis_code'), ['analysis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_proficiency_test_test_date'), ['test_date'], unique=False)

    op.create_table('qc_control_chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_code', sa.String(length=50), nullable=True),
    sa.Column('qc_sample_name', sa.String(length=100), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('ucl', sa.Float(), nullable=True),
    sa.Column('lcl', sa.Float(), nullable=True),
    sa.Column('usl', sa.Float(), nullable=True),
    sa.Column('lsl', sa.Float(), nullable=True),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('measured_value', sa.Float(), nullable=True),
    sa.Column('in_control', sa.Boolean(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qc_control_chart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_control_chart_analysis_code'), ['analysis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_qc_control_chart_measurement_date'), ['measurement_date'], unique=False)

    op.create_table('customer_complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_no', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=False),
    sa.Column('complaint_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_sample_id', sa.Integer(), nullable=True),
    sa.Column('investigated_by_id', sa.Integer(), nullable=True),
    sa.Column('investigation_findings', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('customer_notified', sa.Boolean(), nullable=True),
    sa.Column('customer_satisfied', sa.Boolean(), nullable=True),
    sa.Column('capa_created', sa.Boolean(), nullable=True),
    sa.Column('capa_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['capa_id'], ['corrective_action.id'], ),
    sa.ForeignKeyConstraint(['investigated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['related_sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_complaint_complaint_no'), ['complaint_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_complaint_status'), ['status'], unique=False)

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sampled_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sampling_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sampling_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sampling_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('custody_log', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retention_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('disposal_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('disposal_method', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_column('disposal_method')
        batch_op.drop_column('disposal_date')
        batch_op.drop_column('retention_date')
        batch_op.drop_column('custody_log')
        batch_op.drop_column('sampling_method')
        batch_op.drop_column('sampling_location')
        batch_op.drop_column('sampling_date')
        batch_op.drop_column('sampled_by')

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_complaint_status'))
        batch_op.drop_index(batch_op.f('ix_customer_complaint_complaint_no'))

    op.drop_table('customer_complaint')
    with op.batch_alter_table('qc_control_chart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_control_chart_measurement_date'))
        batch_op.drop_index(batch_op.f('ix_qc_control_chart_analysis_code'))

    op.drop_table('qc_control_chart')
    with op.batch_alter_table('proficiency_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proficiency_test_test_date'))
        batch_op.drop_index(batch_op.f('ix_proficiency_test_analysis_code'))

    op.drop_table('proficiency_test')
    with op.batch_alter_table('environmental_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environmental_log_log_date'))

    op.drop_table('environmental_log')
    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrective_action_status'))
        batch_op.drop_index(batch_op.f('ix_corrective_action_ca_number'))

    op.drop_table('corrective_action')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
