"""Add LabReport and ReportSignature models

Revision ID: 60b0d8da7749
Revises: c365903a2917
Create Date: 2026-02-05 02:00:53.594636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b0d8da7749'
down_revision = 'c365903a2917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('signature_type', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lab_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('lab_type', sa.String(length=30), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sample_ids', sa.JSON(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('analyst_signature_id', sa.Integer(), nullable=True),
    sa.Column('manager_signature_id', sa.Integer(), nullable=True),
    sa.Column('stamp_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_recipients', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyst_signature_id'], ['report_signature.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_signature_id'], ['report_signature.id'], ),
    sa.ForeignKeyConstraint(['stamp_id'], ['report_signature.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number')
    )
    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.create_index('ix_lab_report_lab_status', ['lab_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_report_lab_type'), ['lab_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_report_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_report_status'))
        batch_op.drop_index(batch_op.f('ix_lab_report_lab_type'))
        batch_op.drop_index('ix_lab_report_lab_status')

    op.drop_table('lab_report')
    op.drop_table('report_signature')
    # ### end Alembic commands ###
