"""Add license tables

Revision ID: 649b80ed14bb
Revises: c2718818cc52
Create Date: 2025-12-21 03:54:09.279550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649b80ed14bb'
down_revision = 'c2718818cc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_samples_per_month', sa.Integer(), nullable=True),
    sa.Column('hardware_id', sa.String(length=128), nullable=True),
    sa.Column('allowed_hardware_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=True),
    sa.Column('tampering_detected', sa.Boolean(), nullable=True),
    sa.Column('tampering_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_key')
    )
    op.create_table('license_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_details', sa.Text(), nullable=True),
    sa.Column('hardware_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['system_license.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_log')
    op.drop_table('system_license')
    # ### end Alembic commands ###
