"""Add SolutionPreparation model for water lab

Revision ID: 674fd7eb3ea6
Revises: 19f4cf7409b2
Create Date: 2026-02-04 02:02:25.939994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674fd7eb3ea6'
down_revision = '19f4cf7409b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_preparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_name', sa.String(length=200), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('concentration_unit', sa.String(length=20), nullable=True),
    sa.Column('volume_ml', sa.Float(), nullable=True),
    sa.Column('chemical_used_mg', sa.Float(), nullable=True),
    sa.Column('chemical_id', sa.Integer(), nullable=True),
    sa.Column('prepared_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('v1', sa.Float(), nullable=True),
    sa.Column('v2', sa.Float(), nullable=True),
    sa.Column('v3', sa.Float(), nullable=True),
    sa.Column('v_avg', sa.Float(), nullable=True),
    sa.Column('titer_coefficient', sa.Float(), nullable=True),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('prepared_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_preparation_prepared_by_id'), ['prepared_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_preparation_prepared_date'), ['prepared_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_preparation_solution_name'), ['solution_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_preparation_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_preparation_status'))
        batch_op.drop_index(batch_op.f('ix_solution_preparation_solution_name'))
        batch_op.drop_index(batch_op.f('ix_solution_preparation_prepared_date'))
        batch_op.drop_index(batch_op.f('ix_solution_preparation_prepared_by_id'))

    op.drop_table('solution_preparation')
    # ### end Alembic commands ###
