"""iso17025_operational_user_fk_set_null

Revision ID: 69695d8ac4e9
Revises: 2df88ac7f1d1
Create Date: 2026-05-15 18:04:32.371674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69695d8ac4e9'
down_revision = '2df88ac7f1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bottle_created_by_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bottle_created_by_id', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('bottle_constant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bottle_constant_created_by_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bottle_constant_approved_by_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bottle_constant_approved_by_id', 'user', ['approved_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_bottle_constant_created_by_id', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chemical_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chemical_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chemical_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chemical_usage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chemical_usage_used_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['used_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chemical_waste', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chemical_waste_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chemical_waste_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chemical_waste_record_recorded_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recorded_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('corrective_action_verified_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('corrective_action_technical_manager_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('corrective_action_responsible_person_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['responsible_person_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['technical_manager_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['verified_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customer_complaint_quality_manager_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('customer_complaint_receiver_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('customer_complaint_investigated_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('customer_complaint_complainant_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['quality_manager_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['complainant_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['receiver_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['investigated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('environmental_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('environmental_log_recorded_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recorded_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('equipment_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('improvement_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('improvement_record_technical_manager_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('improvement_record_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['technical_manager_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('instrument_reading', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('instrument_reading_reviewed_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lab_report_created_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lab_report_approved_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['approved_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('maintenance_logs_performed_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['performed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('monthly_plan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('monthly_plan_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('nonconformity_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('nonconformity_record_manager_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('nonconformity_record_responsible_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('nonconformity_record_detector_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['detector_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['manager_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['responsible_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('proficiency_test', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proficiency_test_tested_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tested_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('qc_control_chart', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('qc_control_chart_operator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['operator_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('report_signature', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('report_signature_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solution_preparation_prepared_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['prepared_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('solution_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solution_recipe_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('spare_part_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('spare_part_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('spare_part_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('spare_part_usage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('spare_part_usage_used_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['used_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usage_logs_used_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['used_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usage_logs_used_by_id_fkey'), 'user', ['used_by_id'], ['id'])

    with op.batch_alter_table('spare_part_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('spare_part_usage_used_by_id_fkey'), 'user', ['used_by_id'], ['id'])

    with op.batch_alter_table('spare_part_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('spare_part_log_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('spare_part_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('solution_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solution_recipe_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solution_preparation_prepared_by_id_fkey'), 'user', ['prepared_by_id'], ['id'])

    with op.batch_alter_table('report_signature', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('report_signature_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('qc_control_chart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('qc_control_chart_operator_id_fkey'), 'user', ['operator_id'], ['id'])

    with op.batch_alter_table('proficiency_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proficiency_test_tested_by_id_fkey'), 'user', ['tested_by_id'], ['id'])

    with op.batch_alter_table('nonconformity_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('nonconformity_record_detector_user_id_fkey'), 'user', ['detector_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('nonconformity_record_responsible_user_id_fkey'), 'user', ['responsible_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('nonconformity_record_manager_id_fkey'), 'user', ['manager_id'], ['id'])

    with op.batch_alter_table('monthly_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('monthly_plan_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('maintenance_logs_performed_by_id_fkey'), 'user', ['performed_by_id'], ['id'])

    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lab_report_approved_by_id_fkey'), 'user', ['approved_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lab_report_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('instrument_reading', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('instrument_reading_reviewed_by_id_fkey'), 'user', ['reviewed_by_id'], ['id'])

    with op.batch_alter_table('improvement_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('improvement_record_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('improvement_record_technical_manager_id_fkey'), 'user', ['technical_manager_id'], ['id'])

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('equipment_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('environmental_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('environmental_log_recorded_by_id_fkey'), 'user', ['recorded_by_id'], ['id'])

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customer_complaint_complainant_user_id_fkey'), 'user', ['complainant_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('customer_complaint_investigated_by_id_fkey'), 'user', ['investigated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('customer_complaint_receiver_user_id_fkey'), 'user', ['receiver_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('customer_complaint_quality_manager_id_fkey'), 'user', ['quality_manager_id'], ['id'])

    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('corrective_action_responsible_person_id_fkey'), 'user', ['responsible_person_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('corrective_action_technical_manager_id_fkey'), 'user', ['technical_manager_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('corrective_action_verified_by_id_fkey'), 'user', ['verified_by_id'], ['id'])

    with op.batch_alter_table('chemical_waste_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chemical_waste_record_recorded_by_id_fkey'), 'user', ['recorded_by_id'], ['id'])

    with op.batch_alter_table('chemical_waste', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chemical_waste_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('chemical_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chemical_usage_used_by_id_fkey'), 'user', ['used_by_id'], ['id'])

    with op.batch_alter_table('chemical_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chemical_log_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chemical_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('bottle_constant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bottle_constant_created_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_bottle_constant_approved_by_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bottle_constant_approved_by_id'), 'user', ['approved_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bottle_constant_created_by_id'), 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bottle_created_by_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bottle_created_by_id'), 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###
