"""Add timestamps and user FK to Equipment, MaintenanceLog, UsageLog

Revision ID: 6c49435277bf
Revises: c683ce63af53
Create Date: 2026-02-04 04:53:30.435232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c49435277bf'
down_revision = 'c683ce63af53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_maintenance_logs_performed_by_id'), ['performed_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['performed_by_id'], ['id'])

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usage_logs_used_by_id'), ['used_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['used_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usage_logs_used_by_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('used_by_id')

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_performed_by_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('performed_by_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
