"""Add extra fields to Equipment

Revision ID: 773e711bcb82
Revises: e6b2094bb2e7
Create Date: 2025-11-22 03:59:39.039732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773e711bcb82'
down_revision = 'e6b2094bb2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calibration_note', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manufactured_info', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('commissioned_info', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('initial_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('residual_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('residual_price')
        batch_op.drop_column('initial_price')
        batch_op.drop_column('commissioned_info')
        batch_op.drop_column('manufactured_info')
        batch_op.drop_column('quantity')
        batch_op.drop_column('calibration_note')

    # ### end Alembic commands ###
