"""Add SolutionRecipe and SolutionRecipeIngredient models

Revision ID: 78182c9ac185
Revises: 674fd7eb3ea6
Create Date: 2026-02-04 02:21:58.303060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78182c9ac185'
down_revision = '674fd7eb3ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('concentration_unit', sa.String(length=20), nullable=True),
    sa.Column('standard_volume_ml', sa.Float(), nullable=True),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('lab_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solution_recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_recipe_lab_type'), ['lab_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_recipe_name'), ['name'], unique=False)

    op.create_table('solution_recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['solution_recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_solution_preparation_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_foreign_key(None, 'solution_recipe', ['recipe_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_preparation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_solution_preparation_recipe_id'))
        batch_op.drop_column('recipe_id')

    op.drop_table('solution_recipe_ingredient')
    with op.batch_alter_table('solution_recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_recipe_name'))
        batch_op.drop_index(batch_op.f('ix_solution_recipe_lab_type'))

    op.drop_table('solution_recipe')
    # ### end Alembic commands ###
