"""Add SystemSetting model for config management

Revision ID: 8888c62ea786
Revises: fa36eef8fcc9
Create Date: 2025-11-23 13:37:43.499149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8888c62ea786'
down_revision = 'fa36eef8fcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uq_system_setting_category_key')
    )
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_setting_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_category'))

    op.drop_table('system_setting')
    # ### end Alembic commands ###
