"""update equipment model

Revision ID: 89c8ba0e923e
Revises: 773e711bcb82
Create Date: 2025-11-22 05:41:31.367223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c8ba0e923e'
down_revision = '773e711bcb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_status'), ['status'], unique=False)

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_logs_action_date'), ['action_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_logs_equipment_id'), ['equipment_id'], unique=False)

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_equipment_id'), ['equipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_equipment_id'))

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_action_date'))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_status'))
        batch_op.drop_column('lab_code')

    # ### end Alembic commands ###
