"""Add control standards table

Revision ID: 96e8bcf13076
Revises: c90d3809f42a
Create Date: 2025-11-30 00:28:55.861342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e8bcf13076'
down_revision = 'c90d3809f42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_client_name'))
        batch_op.drop_index(batch_op.f('ix_sample_client_type_status'))
        batch_op.drop_index(batch_op.f('ix_sample_sample_type'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_sample_type'), ['sample_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_client_type_status'), ['client_name', 'sample_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_client_name'), ['client_name'], unique=False)

    op.drop_table('control_standards')
    # ### end Alembic commands ###
