"""Add priority/rule to profiles and name FK constraints

Revision ID: a069a860606f
Revises: 60ad2347e684
Create Date: 2025-11-15 04:34:05.443701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a069a860606f'
down_revision = '73d32cedfaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bottle_serial_no'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_bottle_serial_no'))
        batch_op.create_index(batch_op.f('ix_bottle_serial_no'), ['serial_no'], unique=True)
        batch_op.create_foreign_key('fk_bottle_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('bottle_constant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bottle_constant_avg'))
        batch_op.drop_index(batch_op.f('ix_bottle_constant_bottle'))
        batch_op.create_index(batch_op.f('ix_bottle_constant_avg_value'), ['avg_value'], unique=False)
        batch_op.create_foreign_key('fk_bottle_constant_approved_by_id', 'user', ['approved_by_id'], ['id'])
        batch_op.create_foreign_key('fk_bottle_constant_created_by_id', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_constant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bottle_constant_created_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_bottle_constant_approved_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bottle_constant_avg_value'))
        batch_op.create_index(batch_op.f('ix_bottle_constant_bottle'), ['bottle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bottle_constant_avg'), ['avg_value'], unique=False)

    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bottle_created_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bottle_serial_no'))
        batch_op.create_index(batch_op.f('ix_bottle_serial_no'), ['serial_no'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_bottle_serial_no'), ['serial_no'])

    # ### end Alembic commands ###
