"""Add SparePartCategory model

Revision ID: a1a69125d867
Revises: a74691b93d77
Create Date: 2026-02-04 04:23:50.058359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a69125d867'
down_revision = 'a74691b93d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_part_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_category_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_category_code'))

    op.drop_table('spare_part_category')
    # ### end Alembic commands ###
