"""Add image_path to SparePart

Revision ID: a74691b93d77
Revises: 0d249829b308
Create Date: 2026-02-04 04:04:14.776045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74691b93d77'
down_revision = '0d249829b308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
