"""Add indexes to foreign keys for query performance

Revision ID: aa78006a3112
Revises: 96e8bcf13076
Create Date: 2025-11-30 05:32:44.636561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa78006a3112'
down_revision = '96e8bcf13076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_result_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_result_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_result_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bottle_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('bottle_constant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bottle_constant_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bottle_constant_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_setting_updated_by_id'), ['updated_by_id'], unique=False)

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_sample_id'), ['sample_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_sample_id'))

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_updated_by_id'))

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_user_id'))

    with op.batch_alter_table('bottle_constant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bottle_constant_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_bottle_constant_approved_by_id'))

    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bottle_created_by_id'))

    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_result_log_user_id'))

    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_result_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_result_sample_id'))

    # ### end Alembic commands ###
