"""Add register_type and extra_data to equipment

Revision ID: bf2ed60971e9
Revises: 202601300002
Create Date: 2026-02-01 05:05:33.736743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2ed60971e9'
down_revision = '202601300002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_register_type'), ['register_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_register_type'))
        batch_op.drop_column('extra_data')
        batch_op.drop_column('register_type')

    # ### end Alembic commands ###
