"""Add ondelete SET NULL to sample foreign keys

Revision ID: c2718818cc52
Revises: fdc59c626292
Create Date: 2025-12-18 15:23:04.685486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2718818cc52'
down_revision = 'fdc59c626292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('analysis_result_log_sample_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('analysis_result_log_analysis_result_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'analysis_result', ['analysis_result_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['original_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'sample', ['sample_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_urgent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sample_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_broadcast', sa.Boolean(), nullable=True))
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'sample', ['sample_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customer_complaint_related_sample_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sample', ['related_sample_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('equipment_serial_number_key'), type_='unique')

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_analyses_to_perform'))

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('usage_logs_sample_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sample', ['sample_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usage_logs_sample_id_fkey'), 'sample', ['sample_id'], ['id'])
        batch_op.drop_column('purpose')
        batch_op.drop_column('used_by')

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_analyses_to_perform'), ['analyses_to_perform'], unique=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('equipment_serial_number_key'), ['serial_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('customer_complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customer_complaint_related_sample_id_fkey'), 'sample', ['related_sample_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_broadcast')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('sample_id')
        batch_op.drop_column('is_urgent')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_url')

    with op.batch_alter_table('analysis_result_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analysis_result_log_analysis_result_id_fkey'), 'analysis_result', ['analysis_result_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('analysis_result_log_sample_id_fkey'), 'sample', ['sample_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
