"""Add ChemicalWaste and ChemicalWasteRecord models

Revision ID: c365903a2917
Revises: 6c49435277bf
Create Date: 2026-02-05 01:48:52.498427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c365903a2917'
down_revision = '6c49435277bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_waste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_mn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('disposal_method', sa.String(length=50), nullable=True),
    sa.Column('disposal_location', sa.String(length=255), nullable=True),
    sa.Column('is_hazardous', sa.Boolean(), nullable=True),
    sa.Column('hazard_type', sa.String(length=100), nullable=True),
    sa.Column('lab_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chemical_waste_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waste_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('starting_balance', sa.Float(), nullable=True),
    sa.Column('ending_balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['waste_id'], ['chemical_waste.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('waste_id', 'year', 'month', name='uq_waste_year_month')
    )
    with op.batch_alter_table('chemical_waste_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_waste_record_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_waste_record_waste_id'), ['waste_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_waste_record_year'), ['year'], unique=False)
        batch_op.create_index('ix_waste_record_year_month', ['year', 'month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical_waste_record', schema=None) as batch_op:
        batch_op.drop_index('ix_waste_record_year_month')
        batch_op.drop_index(batch_op.f('ix_chemical_waste_record_year'))
        batch_op.drop_index(batch_op.f('ix_chemical_waste_record_waste_id'))
        batch_op.drop_index(batch_op.f('ix_chemical_waste_record_month'))

    op.drop_table('chemical_waste_record')
    op.drop_table('chemical_waste')
    # ### end Alembic commands ###
