"""Add equipment_id to SparePartCategory

Revision ID: c683ce63af53
Revises: a1a69125d867
Create Date: 2026-02-04 04:30:30.201670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c683ce63af53'
down_revision = 'a1a69125d867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipment_id')

    # ### end Alembic commands ###
