"""Add SparePartLog.data_hash

Revision ID: cc4575a03dfb
Revises: 60b0d8da7749
Create Date: 2026-02-05 05:27:00.515765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4575a03dfb'
down_revision = '60b0d8da7749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_part_log', schema=None) as batch_op:
        batch_op.drop_column('data_hash')

    # ### end Alembic commands ###
