"""Add analyses_json to AnalysisProfile

Revision ID: e6b2094bb2e7
Revises: 14795e47a81c
Create Date: 2025-11-20 18:33:46.507307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b2094bb2e7'
down_revision = '14795e47a81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=True),
    sa.Column('analyses_json', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('match_rule', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_profiles_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profiles_pattern'), ['pattern'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profiles_profile_type'), ['profile_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profiles_sample_type'), ['sample_type'], unique=False)

    with op.batch_alter_table('analysis_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_profile_client_name'))
        batch_op.drop_index(batch_op.f('ix_analysis_profile_pattern'))
        batch_op.drop_index(batch_op.f('ix_analysis_profile_profile_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_profile_sample_type'))

    op.drop_table('analysis_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sample_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=200), nullable=True),
    sa.Column('analyses', sa.TEXT(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('match_rule', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_profile_sample_type'), ['sample_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profile_profile_type'), ['profile_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profile_pattern'), ['pattern'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_profile_client_name'), ['client_name'], unique=False)

    with op.batch_alter_table('analysis_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_profiles_sample_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_profiles_profile_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_profiles_pattern'))
        batch_op.drop_index(batch_op.f('ix_analysis_profiles_client_name'))

    op.drop_table('analysis_profiles')
    # ### end Alembic commands ###
