"""add user language column

Revision ID: f495c2b86f6d
Revises: 4d9f2eb4a65c
Create Date: 2026-02-17 17:33:28.253544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f495c2b86f6d'
down_revision = '4d9f2eb4a65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['technical_manager_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('corrective_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
