"""add category column to equipment

Revision ID: fa36eef8fcc9
Revises: 3fc3552c3075
Create Date: 2025-11-22 17:42:35.830459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa36eef8fcc9'
down_revision = '3fc3552c3075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
